### ISSUE TITLE
Guest invite settings

### ISSUE THREAD

**Issue by DaveZimmermann** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#4] opened 2021-06-04 06:37 UTC
# Module: 01
#### Step: 05

Description of issue
Azure AD Guest Invite Settings look now different in new tenants.
Now: 
Guest invite settings
Guest invite restrictions
Learn more
	Anyone in the organization can invite guest users including guests and non-admins (most inclusive)
	Member users and users assigned to specific admin roles can invite guest users including guests with member permissions
	Only users assigned to specific admin roles can invite guest users
	No one in the organization can invite guest users including admins (most restrictive)

Repro steps:

1. just check https://portal.azure.com/#blade/Microsoft_AAD_IAM/CompanyRelationshipsMenuBlade/Settings in a tenant. Please update Screenshot and the instructions.

**Comment by R-C-Stewart** [comment] 2021-09-10 21:59
This should be fixed with the lab update submitted today (9/10/2021).  If the issue is not resolved, please let me know.

**Closed by R-C-Stewart** 2021-09-10 21:59 UTC
